# Exercise 1.A NumPy: Manipulating Arrays

In [98]:
import numpy as np

## Looping Through Arrays

In [53]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [54]:
for x in arrA:
    print(x)

for x in arrA:
    print(x * 2)

[11 12 13]
[14 15 16]
[22 24 26]
[28 30 32]


In [55]:
for y in arrA:
    print(y)

for y in arrA:
   print(y * 2)

[11 12 13]
[14 15 16]
[22 24 26]
[28 30 32]


There's no difference between the outputs themselves - it lists the arrays in the same order. The main difference between the first array and the second array lie in the values - for example, x = 11, 12 and 13 while x * 2 = 22, 24, 26.

## Joining and Stacking Arrays

In [56]:
joined_array_1 = arrA + arrA.sum(axis=0)
print(joined_array_1) 

[[36 39 42]
 [39 42 45]]


In [57]:
joined_array_2 = arrA.sum(axis=1, keepdims=True) + arrA
print(joined_array_2)

[[47 48 49]
 [59 60 61]]


In [58]:
stacked_array_1 = joined_array_1 + arrA.sum(axis=0)
print(stacked_array_1)

[[61 66 71]
 [64 69 74]]


In [59]:
stacked_array_2 = joined_array_2 + arrA.sum(axis=1, keepdims=True)
print(stacked_array_2)

[[ 83  84  85]
 [104 105 106]]


In [60]:
another_joined_array = arrA + joined_array_1
print(another_joined_array)

[[47 51 55]
 [53 57 61]]


In [64]:
another_2 = joined_array_1 + arrA(axis=1)
print(another_2)

TypeError: 'numpy.ndarray' object is not callable

The type error that comes back describes the numpy.ndarray object as un-callable. 

In [70]:
array1 = np.hstack(arrA)
array2 = np.vstack(arrA)
array3 = np.dstack(arrA)

print(array1)
print(array2)
print(array3)

[11 12 13 14 15 16]
[[11 12 13]
 [14 15 16]]
[[[11 14]
  [12 15]
  [13 16]]]


## Splitting Arrays

In [72]:
splitsky = np.array_split(joined_array_1, 2)

In [73]:
print(splitsky)
#

[array([[36, 39, 42]]), array([[39, 42, 45]])]


In [74]:
spliterino = np.array_split(joined_array_1, 3)

In [75]:
print(spliterino)
#

[array([[36, 39, 42]]), array([[39, 42, 45]]), array([], shape=(0, 3), dtype=int64)]


## Searching and Replacing Array Values.

In [90]:
numbers = [36, 39, 42, 39, 42, 45]
result_1 = [n for n in numbers if n % 2 == 0]
print(result_1)

[36, 42, 42]


## Sorting and Filtering Arrays

In [114]:
arrB = np.array([7, 6, 13, 5, 7, 3])
arrB_sorted = sorted(arrB)
print(arrB_sorted)

[np.int64(3), np.int64(5), np.int64(6), np.int64(7), np.int64(7), np.int64(13)]


In [115]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[ 7  6 13  5  7  3]
[6 5 3]


In [117]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
