# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [8]:
r_1 = np.random.randint(1, 20, size=(2))
print(r_1)

[2 8]


In [12]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[9 2]]


In [30]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.92237063]
 [0.650792  ]]


In [14]:
r_4 = np.random.randint(1, 20, size=(4, 5))
print(r_4)

[[18  1  8 18  4]
 [10 14 14  4  2]
 [ 4 11 17 13  8]
 [ 2 16 15 14  2]]


In [28]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.93705384 0.65321784 0.63869787 0.54161743 0.89536484]
 [0.91194203 0.20277303 0.07575629 0.20660795 0.39422058]
 [0.17320148 0.57633346 0.2581503  0.07375775 0.86377941]
 [0.39886387 0.92905435 0.33155235 0.17145328 0.38836019]]


## Generating Random Choices from an Array

In [43]:
students = np.array(["Marenza", "Dania", "Cris", "Maia", "Leon", "Dmitri", "Sharleen", "Aspenne", "Patrick", "Jordan", "Hamzah", "Ivana"])
call_on = np.random.choice(students, size=1), 
print(call_on)

['Sharleen']


In [47]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)
# # This would not be an effective way to assign breakout groups. In the example printed below, there are doubles of names that are randomly generated.
# # Names can be generated twice, but you are unable to assign someone to two breakout rooms at once. 

[['Aspenne' 'Dmitri' 'Hamzah' 'Hamzah']
 ['Marenza' 'Hamzah' 'Marenza' 'Leon']
 ['Maia' 'Jordan' 'Sharleen' 'Patrick']]


In [76]:
call_on_weighted = np.random.choice(
    ["Marenza", "Dania", "Cris", "Maia", "Leon", "Dmitri", "Sharleen", "Aspenne", "Patrick", "Jordan", "Hamzah", "Ivana"],
        p=[0.1, 0.2, 0.1, 0.0, 0.3, 0.0, 0.2, 0.0, 0.1, 0.0, 0.0, 0.0], size=(1))
print(call_on_weighted)
# # I chose all of the float percents at random. I had to make sure that all of them added up to 1, so that the code would work properly. 

['Dania']


## Generating a Normal Distribution

In [77]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[17.2472233   8.32261212  2.85572125  4.85816664 15.67209679]
 [14.93216427 11.68908104 19.09829936 14.36174789  7.2024396 ]
 [ 4.75811658  5.4190654  15.45390226  8.83210781 11.57335604]
 [ 9.05423187 13.04773782  2.41635909  4.49690323 14.41502828]]
